In [37]:
#NUMPY ####################################

In [4]:
#need to import before you use package
import numpy as np

#create numpy array and python list
a = np.array([1, 2, 3, 4, 5])
list = [1, 2, 3, 4, 5]

In [6]:
a

array([1, 2, 3, 4, 5])

In [7]:
list

[1, 2, 3, 4, 5]

In [9]:
#element wise operations with numpy arrays
print(a+5)

[ 6  7  8  9 10]


In [10]:
print(a*2)

[ 2  4  6  8 10]


In [11]:
#these operations are not supported with python lists
print(list+5)

TypeError: can only concatenate list (not "int") to list

In [ ]:
#this is how you do those operations with python lists

In [15]:
newlist = []
for e in list: 
    m = e+2
    newlist.append(m)
newlist

[3, 4, 5, 6, 7]

In [12]:
print(list*2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [17]:
#indexing and slicing with numpy arrays
#indexing is getting 1, slicing is getting a range
print(a[1])

2


In [18]:
#when you slice, it includes the first index value, but does not include the last index value
print(a[1:4])

[2 3 4]


In [19]:
print(list[1])

2


In [20]:
print(list[1:4])

[2, 3, 4]


In [21]:
#arrays don't have commas, lists do

In [22]:
childage = np.array([6, 8, 11, 13, 17])

In [23]:
print(childage)

[ 6  8 11 13 17]


In [24]:
childage

array([ 6,  8, 11, 13, 17])

In [25]:
parentage = childage+30

In [26]:
parentage

array([36, 38, 41, 43, 47])

In [27]:
(parentage*2)-childage

array([66, 68, 71, 73, 77])

In [28]:
parentageresult = (parentage*2)-childage

In [29]:
parentageresult

array([66, 68, 71, 73, 77])

In [32]:
#arrays have to be homogenous
test = np.array([1, 2, "2"])

In [33]:
test

array(['1', '2', '2'], dtype='<U21')

In [34]:
#when they aren't homogenous, it automatically converts everything into one form

In [36]:
#PYTHON FUNCTIONS #########################################################

In [38]:
#def means define (your function)

In [39]:
def function_name(arguments):
    # Function body
    result = perform_some_operations(arguments)
    return result

In [43]:
def greet(name):
    return f"Hello, {name}!"

print(greet("Asha"))

Hello, Asha!


In [44]:
def add(a, b):
        return a + b
    
print(add(3, 5))

8


In [47]:
def testing(a, b, c):
    c = a + c
    b = c/b
    return b

a = 2
c = 10
b = 3
testing(a, b, c)

4.0

In [48]:
def power(base, exponent=2):
    return base ** exponent

In [49]:
print(power(3))

9


In [50]:
print(power(3, 3))

27


In [51]:
#in line 50, we overwrote what the exponent was supposed to be (it was supposed to be 2)

In [53]:
def multiply(a, b): 
    return a * b
print(multiply(7, 3))

21


In [54]:
#can't define a function called list, dict, etc. because python already uses those, blue ones are fine to use and green are not fine to use

In [61]:
def getmax(alist):
    for i in range(len(alist)):
        previouselement= alist[i-1]
        currentelement= alist[i]
        print(i, previouselement, currentelement)
        if previouselement >= currentelement:
            maxelement = previouselement
        else:
            maxelement=currentelement
        print(maxelement)
    return maxelement
blist = [1, 3, 5, 7]
clist = [17, 6, 12, 4]

In [62]:
getmax(alist=blist)

0 7 1
7
1 1 3
3
2 3 5
5
3 5 7
7


7

In [63]:
getmax(alist=clist)

0 4 17
17
1 17 6
17
2 6 12
12
3 12 4
12


12

In [64]:
#PYTHON MODULES ###############################

In [65]:
#first have to import modules using import module_name
#access by result = module_name.function_name(arguments)

In [67]:
import math
#calculate square root of 16
sqrtresult = math.sqrt(16)
print(sqrtresult)

4.0


In [68]:
#calculate cosine of 45 degrees
cosresult = math.cos(math.radians(45))
print(cosresult)

0.7071067811865476


In [69]:
#can import specific function from a module, not whole module

In [70]:
from math import sqrt

In [71]:
sqrtresult = sqrt(16)

In [72]:
print(sqrtresult)

4.0


In [73]:
#to use shorter name of module, import it with an alias using the as keyword

In [74]:
import math as m

In [75]:
sqrtresult = m.sqrt(16)
print(sqrtresult)

4.0
